# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      cargo:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: monthly
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
