# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

FROM gcr.io/distroless/cc-debian13:nonroot
ARG TARGETARCH

COPY dist/${TARGETARCH}/opensovd-mcp /usr/local/bin/opensovd-mcp

WORKDIR /tmp
ENTRYPOINT ["/usr/local/bin/opensovd-mcp"]
